-- Borrar tot
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `e_obres`;
TRUNCATE `e_museus`;
TRUNCATE `e_autors`;
TRUNCATE `e_comments`;
SET FOREIGN_KEY_CHECKS=1;

-- Museus  
INSERT INTO `e_museus` VALUES 
-- id, nom, direccio, latitud, longitud, telefon, hora_laboral_inici, hora_laboral_fi, hora_festiu_inici, hora_festiu_fi, wifi_ssid, wifi_password, valoracio, num_valoracions, descripcio, imatge
-- 1
(NULL, 'Museu Picasso', 'Barcelona, C/ Montcada 15-23', 41.3853269, 2.180524699999978, '932563000', '', '', '', '', '', '', 0, 0,
'Picasso vivió en Barcelona unos años fundamentales: los de su periodo de formación. Con Barcelona estableció y mantuvo unos fuertes vínculos durante toda su vida. En Barcelona quiso tener su museo.
Así fue como, en 1960, y por voluntad expresa del propio Picasso, su amigo y secretario personal, Jaume Sabartés, propuso al Ayuntamiento de Barcelona la creación de un museo dedicado a su obra. En 1963 el museo era una realidad y abría sus puertas en el Palacio Aguilar, en el número 15 de la calle de Montcada.
El fondo del museo lo integraban en aquel momento la colección personal de Sabartés y la colección de obras de Picasso de los Museos de Arte de Barcelona (básicamente el Arlequín, la colección Plandiura, el legado de dibujos del coleccionista Lluís Garriga Roig, la serie de grabados para Las metamorfosis de Ovidio y varias litografías y carteles).
Actualmente el Museu Picasso de Barcelona es el centro de referencia para el conocimiento de los años de formación de Pablo Ruiz Picasso.Acoge un fondo de 4.249 obras, que componen la colección permanente, y ofrece una dilatada programación de exposiciones temporales.Pero el Museu Picasso también es el testimonio de su vínculo con Barcelona. 
Un vínculo estrecho e inseparable, forjado en su adolescencia y su juventud, y que se prolongó hasta su muerte. La máxima expresión de su fuerte vinculación con la ciudad es el propio Museu Picasso de Barcelona, creado por voluntad personal del artista: gracias a la voluntad de Picasso y de su amigo Jaume Sabartés, Barcelona dispone hoy de la obra de juventud, así como de la serie completa de Las Meninas, de uno de los artistas más significativos de la escena artística del siglo xx.
El museo, que ha pasado por sucesivas ampliaciones y remodelaciones, está iniciando una nueva etapa de despliegue, con la apertura de nuevos programas y líneas de acción, para convertirse en un espacio básico para el conocimiento y la educación en el sentido más amplio, que fomente el espíritu crítico y la participación del visitante. El museo quiere ser un espacio de diálogo, activando relecturas críticas y ofreciendo nuevas perspectivas en torno a Picasso y la colección en general.Entre sus colecciones destacan obras como Hombre con Boina,Paisaje montañoso,Retrato de la tía Pepa,etc.',
 'http://www.museupicasso.bcn.cat/imatges/home2012/logo-museu-picasso.png'),
-- 2
(NULL, 'Museu Dalí', 'Figueres, Plaza Gala-Salvador Dalí, 5', 42.2680868, 2.9598813000000064, '972677500', '', '', '', '', '', '', 0, 0, 
'El Teatro-Museo Dalí hay que verlo como un todo, como la gran obra de Salvador Dalí(1904-1989), ya que todo en él fue diseñado por el artista con la finalidad de ofrecer al visitante una verdadera experiencia y sumergirlo en su mundo cautivador y único. 
El edificio del teatro de la ciudad de Figueres, obra del arquitecto Roca i Bros, fue construido entre 1849 y 1850 pero fue destruido por un incendio al final de la guerra civil española, en 1939.
Desde ese momento el edificio había quedado reducido a su estructura sustentante periférica. El techo de la platea se había hundido, de los palcos sólo quedaban los pasillos de acceso, y del escenario, el arco de la boca de escena y los almacenes laterales. El vestíbulo y el salón de descanso fueron las únicas partes que se mantuvieron en gran medida intactas. A pesar de todo, puede afirmarse que la estructura elemental del teatro se mantuvo y había dejado a Figueres una ruina de aspecto fantasmagórico.
En 1961, el entonces alcalde de la ciudad, Ramon Guardiola, propuso a Salvador Dalí hacer un museo dedicado a su obra. El pintor quedó fascinado por el encanto espectral del teatro y, con la intención de mantener la estructura del edificio, lo escogió como sede del futuro Teatro-Museo Dalí.
La idea de reunir su obra en el antiguo teatro de Figueres entusiasmó a Dalí y el artista se entregó a la tarea durante más de una década, interviniendo y diseñando los detalles más mínimos, hasta convertirlo en realidad con la inauguración oficial del Teatro-Museo Dalí el 28 de septiembre de 1974. Uno de los elementos más visibles del museo es la estructura reticular transparente en forma de cúpula geodésica que corona el edificio, una idea de Salvador Dalí que realizó el arquitecto murciano Emilio Pérez Piñero (1935-1972). La cúpula se ha convertido no sólo en el emblema del Teatro-Museo sino en todo un símbolo para la ciudad de Figueres.
Algunas de las obras más remarcables que allí se exponen son:Port Alguer (1924), Muchacha de Figueres (1926), El espectro del Sex-appeal (1932), Autorretrato blando con beicon frito (1941),Poesía de América-Los atletas cósmicos (1943), Galarina (1944-45), La cesta de pan (1945), La nariz de Napoleón transformada en una mujer encinta que pasea su sombra melancólica entre las ruinas originales (1945), Leda atómica (1949), La apoteosis del dólar (1965), Galatea de las esferas (1952), o Aurora, mediodía, atardecer y crepúsculo (1979). 
También cabe destacar el conjunto de obras realizadas por el artista expresamente para el Teatro-Museo, como la Sala Mae West, la Sala Palacio del Viento, el Monumento a Francesc Pujols y el Cadillac lluvioso. También se muestran obras de otros artistas que Salvador Dalí quiso incluir: El Greco, Marià Fortuny, Modest Urgell, Ernest Meissonier, Marcel Duchamp, Wolf Wostell, Antoni Pitxot y Evarist Vallès, entre otros. ', 
'https://www.salvador-dali.org/media/comu/logo_figueres.gif'),
-- 3
(NULL, 'Caixa Forum', 'Barcelona, Av. Francesc Ferrer i Guàrdia, 6-8', 41.3711448, 2.1493874000000233, '934768600', '', '', '', '', '', '', 0, 0, 
'CaixaForum, el centro social y cultural de la Obra Social "la Caixa", está ubicado en uno de los principales edificios modernistas de Barcelona. Se trata de una fábrica textil singular, ubicada en los pies de la montaña de Montjuïc, que el empresario Casimir Casaramona encargó al arquitecto Puig i Cadafalch, uno de los tres arquitectos catalanes más representativos del modernismo, contemporáneo de Domènech i Montaner y Antoni Gaudí. El edificio es una pieza única de la arquitectura modernista industrial catalana de principios del siglo XX. 
Tras una larga temporada de inactividad, "la Caixa" adquirió el edificio en 1963, y en 1992 decidió devolverlo a Barcelona y al Estado en general, otorgándole una nueva función de cariz social, cultural y educativo y dotándolo de las infraestructuras propias de un moderno equipamiento cultural, sin estropear el espíritu original de la obra. Así, en 2002 nace CaixaForum. En el proyecto de restauración y ampliación colaboraron los arquitectos de renombre internacional Arata Isozaki, Francisco Javier Asarta, Roberto Luna y Robert Brufau. 
El centro cuenta en la actualidad con 12.000 m², distribuidos en tres plantas, y de estos, más de 2.500 están ocupados por las cuatro salas de exposiciones.
CaixaForum ofrece una amplia oferta de programas sociales, culturales y educativos. Abierto a todo tipo de público, CaixaForum se ha convertido en uno de los espacios culturales más dinámicos, activos y vivos de la ciudad en el que pueden visitarse exposiciones temporales de arte antiguo, moderno y contemporáneo. Especial mención merece la Colección de Arte Contemporáneo de la Obra Social "la Caixa", una de las más importantes del Estado español, que se exhibe en CaixaForum en forma de muestras temporales.
Una permanente programación de conciertos, proyecciones de cine, debates y conferencias, espectáculos de artes escénicas, ciclos de literatura y pensamiento, arte multimedia y programas familiares convierten CaixaForum en un centro de referencia. ', 
'http://obrasocial.lacaixa.es/deployedfiles/obrasocial/Estaticos/imagenes/Nuestros_centros/caixaforumbarcelona.gif'),
-- 4
(NULL, 'Fundació Joan Miró', 'Barcelona, Parc de Montjuïc s/n', 41.3686111, 2.163055600000007, '934439470', '', '', '', '', '', '', 0, 0, 
'La Fundació Joan Miró abrió sus puertas al público el 10 de junio de 1975. Sus orígenes están ligados a la primera gran exposición de Joan Miró en Barcelona, en 1968, en el antiguo Hospital de la Santa Creu. Diversas personalidades del mundo del arte y la cultura comprendieron entonces la oportunidad histórica de disponer, en Barcelona, de un espacio de referencia de la obra de Miró. Conforme a la voluntad del artista, la nueva institución debía fomentar el conocimiento y la difusión del arte más actual en todas sus vertientes.En un momento en que el panorama artístico y cultural era ciertamente exiguo, la Fundació Joan Miró aportó vitalidad, con un nuevo concepto de museo, más dinámico, donde la creación de Miró convivía con las manifestaciones artísticas más diversas, carácter que quedaba reflejado en el epígrafe CEAC (Centro de Estudios de Arte Contemporáneo).Recientemente la Fundación ha sido declarada museo de interés nacional por la relevancia de su patrimonio. 
El edificio de la Fundació es obra de Josep Lluís Sert, arquitecto cofundador del GATCPAC (Grupo de Arquitectos y Técnicos Catalanes para el Progreso de la Arquitectura Contemporánea) y gran amigo de Joan Miró. Fue levantado en unos terrenos cedidos por el Ayuntamiento de Barcelona en el Parc de Montjuïc.
Hacia finales de los años sesenta, Sert y Miró empezaron a pensar y a trabajar en el proyecto de un "Museo Miró" en dicho emplazamiento. Ya en los primeros bocetos de Sert, la Fundació seguía los principios de la arquitectura racionalista, con espacios distribuidos alrededor de un patio central, un rasgo característico de la arquitectura mediterránea, y los lucernarios habituales en la obra de Sert. Diseñado para albergar la colección de Joan Miró, el edificio ha demostrado también su capacidad y adaptabilidad para exhibir las creaciones de otros artistas de los siglos XX y XXI, y es aún un paradigma de la arquitectura contemporánea.
En 1988, el edificio de la Fundació fue ampliado con el fin de ganar espacio expositivo, lo que dio cabida a nuevos servicios y permitió reubicar las oficinas. La ampliación fue proyectada por Jaume Freixa, amigo y discípulo de Sert.  ', 
'http://www.fundaciomiro-bcn.org/img/logoJoanMiro.jpg'),
-- 5
(NULL, 'MACBA: Museu d''Art Contemporani de Barcelona', 'Barcelona, Plaça dels Àngels, 1', 41.3830973, 2.1675153999999566, '934120810', '', '', '', '', '', '', 0, 0,
 'El Museu d’Art Contemporani de Barcelona (MACBA) abrió sus puertas el 28 de noviembre de 1995. Desde entonces se ha consolidado internacionalmente como un modelo en el arte contemporáneo: por una parte, su colección ha experimentado un crecimiento considerable, que en la actualidad permite trazar un recorrido por algunos de los referentes artísticos de nuestro tiempo; y por otra, ha desarrollado unas líneas de trabajo, basadas en la asunción de riesgos y la voluntad de ejercer de laboratorio, que lo han posicionado como un centro clave en el ámbito de la investigación y en la generación de nuevas dinámicas para el análisis y la reflexión sobre la actividad artística.
Los antecedentes del actual Museu d’Art Contemporani de Barcelona se remontan a 1959, año en el que el crítico de arte Alexandre Cirici Pellicer defendió la necesidad de crear un museo de arte contemporáneo en la ciudad. Alexandre Cirici y Cesáreo Rodríguez-Aguilera, junto a varias personalidades, comenzaron a reunir una colección con el objetivo de que sirviera de base para el futuro museo. Mientras buscaban un emplazamiento definitivo, organizaron una serie de exposiciones con artistas del momento: Antoni Bonet, Jordi Curós, Jean Fautrier, Ángel Ferrant, August Puig, Albert Ràfols-Casamada, Josep Maria de Sucre, Romà Vallès, Moisès Villèlia, etc. Pero en febrero de 1963, la exposición L''art i la pau –políticamente comprometida– evidenció los límites de permisividad existentes y puso fin a la aventura de Cirici y Rodríguez- Aguilera. Parte de los fondos fueron a parar al Museu Víctor Balaguer de Vilanova i la Geltrú. 
En 1985, el conseller de Cultura de la Generalitat de Catalunya, Joan Rigol, recuperó la idea del museo de arte contemporáneo, compartida por los responsables municipales del Área de Cultura, encabezados por Pep Subirós. El texto del Pacto Cultural, promovido por Rigol y consensuado por ambas administraciones, ratificó la creación de un consorcio constituido por la Generalitat de Catalunya y el Ayuntamiento de Barcelona para crear un museo en la antigua Casa de la Caritat. Pero el relevo del conseller pocos meses después frenó el proyecto. En 1986 el Ayuntamiento de Barcelona, con Pasqual Maragall al frente, encargó al arquitecto norteamericano Richard Meier la construcción de la sede del nuevo museo. Por su lado, los críticos Francesc Miralles y Rosa Queralt redactaron la memoria en la que se definían sus bases conceptuales. 
Finalmente, en 1987, se constituyó la Fundación Museu d’Art Contemporani de Barcelona, presidida por el empresario Leopoldo Rodés, que suponía la incorporación de la iniciativa privada en el proyecto. El nuevo museo nació en abril de 1988 con la creación del Consorcio del Museu d’Art Contemporani de Barcelona, integrado por la Generalitat de Catalunya, el Ayuntamiento de Barcelona y la Fundació Museu d’Art Contemporani de Barcelona. El MACBA se inauguró públicamente el 28 de noviembre de 1995. 
En 2007 el Ministerio de Cultura se incorpora en el Consorcio y el 14 de abril de 2008 el Consejo General del Consorcio aprueba unos nuevos estatutos que definen su estructura. Las tres administraciones públicas que integran el Consorcio aportan los recursos necesarios para el funcionamiento ordinario del Museo, mientras que la Fundación MACBA tiene como finalidad generar los recursos económicos para configurar su propia colección. Desde su creación hasta la actualidad, el MACBA ha sido dirigido por Daniel Giralt-Miracle (1988-1994), Miquel Molins (1995-1998), Manuel J. Borja-Villel (1998-2007) y Bartomeu Marí (desde 2008).', 
 'http://www.descubrirelarte.es/wp-content/uploads/2012/04/Logo_Macba_recortado.jpg'),
 -- 6
 (NULL,'Museo Nacional de Arte de Cataluña','Barcelona,Palau Nacional, Parc de Montjuïc, s/n',41.3684399,2.153569999999945,'936220360','','','','','','',0,0,
 'El Museo Nacional de Arte de Cataluña (en catalán: Museu Nacional d''Art de Catalunya), también conocido por sus siglas MNAC, está situado en la ciudad de Barcelona, (España). Destaca por su colección de arte Románico, considerada una de las más completas del mundo. Su director es Josep Serra i Villalba.
El actual museo se constituyó en 1990 con la unión de las colecciones del Museo de Arte Moderno, creado en 1945, y el Museo de Arte de Cataluña, inaugurado en 1934. A las piezas procedentes de estos museos se les añadieron una nueva sección denumismática, otra de grabados así como los fondos de la Biblioteca General de Historia del Arte. Más tarde, en 1996, se añadió un nuevo departamento dedicado a la fotografía. En 2006 el fondo del museo poseía ya casi 250.000 obras en las diferentes colecciones. Además de las exposiciones temporales y de las itinerantes, el museo realiza también otras funciones como son las de estudio, conservación y restauración de obras de arte.
El MNAC es un consorcio constituido por la Generalidad de Cataluña, el Ayuntamiento de Barcelona y, desde principios de 2005, la Administración General del Estado.3 En el patronato del museo están representadas, además de las administraciones públicas, los particulares y las entidades privadas que colaboran con el museo.
La sede principal se encuentra ubicada en el Palacio Nacional, edificio situado en la montaña de Montjuïc, inaugurado en 1929con motivo de la Exposición Internacional celebrada en la Ciudad Condal. Además, otras tres instituciones forman parte del conjunto del museo: la Biblioteca Museo Víctor Balaguer de Villanueva y la Geltrú; el Museo Comarcal de la Garrotxa en Olot; y elMuseo Cau Ferrat de Sitges.',
 'http://www.upf.edu/art-africa/_img/logo_mnac.jpg'),
 
 -- 7
 (NULL,'Museo Nacional Centro de Arte Reina Sofía','Madrid,Calle Santa Isabel 52',40.4085636,-3.6940349000000197,'917741000 ','','','','','','',0,0,
 'El Museo Nacional Centro de Arte Reina Sofía (MNCARS) es un museo español de arte del siglo XX y contemporáneo, con sede en Madrid. Su nombre se abrevia frecuentemente como Museo Reina Sofía.
Tomó como sede el antiguo Hospital General de Madrid, gran edificio neoclásico del siglo XVIII situado en la zona de Atocha, cerca de las estaciones homónimas de tren y metro. Este hospital fue diseñado inicialmente por José de Hermosilla y continuado posteriormente por Francesco Sabatini, y actualmente se le conoce como edificio Sabatini en honor a este arquitecto italiano. El museo fue inaugurado en 1992.
El Reina Sofía es el vértice sur del conocido como Triángulo del Arte de Madrid, que incluye a otros dos célebres museos: elPrado y el Thyssen-Bornemisza.
En la colección permanente del museo destaca un núcleo de obras de grandes artistas españoles del siglo XX, especialmentePablo Picasso, Salvador Dalí y Joan Miró, representados ampliamente y con algunas de sus mejores obras. Son muy relevantes también las colecciones de arte surrealista (con obras de Francis Picabia, René Magritte, Óscar Domínguez o Yves Tanguy, además de los ya citados Miró y Dalí), del Cubismo (que a la colección Picasso añade nombres como Juan Gris, Georges Braque,Robert Delaunay o Fernand Léger), y la presencia de artistas expresionistas, como Francis Bacon o Antonio Saura.
Junto a estos autores hay muchos otros de diversas tendencias tan destacados como Lucio Fontana, Yves Klein, Diego Rivera,Alexander Calder, Roberto Matta, Mark Rothko, Antonio López García, Antoni Tàpies, Miquel Barceló o Sam Francis.',
 'http://www.museoreinasofia.es/sites/all/themes/mrs_twitter_bootstrap/logo.png'),
 
 -- 8
 (NULL,'Museo Nacional del Prado','Madrid,Paseo del Prado, s/n',40.413782,-3.692127400000004,'913302800 ','','','','','','',0,0,
 'El Museo Nacional del Prado, en Madrid, España, es uno de los más importantes del mundo,así como uno de los más visitados (el undécimo en 2010).Alfonso E. Pérez Sánchez, antiguo director de la institución, afirmaba que «representa a los ojos del mundo lo más significativo de nuestra cultura y lo más brillante y perdurable de nuestra historia»
Singularmente rico en cuadros de maestros europeos de los siglos XVI al XIX (según el historiador del arte e hispanistaestadounidense Jonathan Brown «pocos se atreverían a poner en duda que es el museo más importante del mundo en pintura europea»),su principal atractivo radica en la amplia presencia de Velázquez, El Greco, Goya (el artista más extensamente representado en la colección),Tiziano, Rubens y El Bosco, de los que posee las mejores y más extensas colecciones que existen a nivel mundial, a lo que hay que sumar destacados conjuntos de autores tan importantes como Murillo, Ribera,Zurbarán, Rafael, Veronese, Tintoretto o Van Dyck, por citar solo algunos de los más relevantes.
Por crónicas limitaciones de espacio, el museo exhibía una selección de obras de máxima calidad (unas 900), por lo que era definido como «la mayor concentración de obras maestras por metro cuadrado». Con la ampliación de Rafael Moneo, se previó que la selección expuesta crecería en un 50%, con unas 450 obras más.En julio de 2011, muy avanzada la reorganización de las salas, la exhibición permanente ha sumado unas 300 obras, por lo que el total expuesto llega a 1.150, de un inventario de más de 8.600.Además de las pinturas, el Prado posee alrededor de 950 esculturas, 8.200 dibujos, 4.200 grabados, 800 objetos de artes decorativas, 900 monedas y 800 medallas.13 14
Al igual que otros grandes museos europeos, como el Louvre de París y los Uffizi de Florencia, el Prado debe su origen a la afición coleccionista de las dinastías gobernantes a lo largo de varios siglos. Refleja los gustos personales de los reyes españolesy su red de alianzas y sus enemistades políticas, por lo que es una colección asimétrica, insuperable en determinados artistas y estilos, y limitada en otros. Sólo desde el siglo XX se procura, con resultados desiguales, solventar las ausencias más notorias.
El Prado no es un museo enciclopédico al estilo del Museo del Louvre, el Hermitage, la National Gallery de Londres, o incluso (a una escala mucho más reducida) el vecino Museo Thyssen-Bornemisza, que tienen obras de prácticamente todas las escuelas y épocas. Por el contrario, es una colección intensa y distinguida, formada esencialmente por unos pocos reyes aficionados al arte, donde muchas obras fueron creadas por encargo. El núcleo procedente de la Colección Real se ha ido complementando con aportaciones posteriores, que apenas han desdibujado su perfil inicial. Muchos expertos la consideran una colección «de pintores admirados por pintores», enseñanza inagotable para nuevas generaciones de artistas, desde Manet, Renoir y Toulouse-Lautrec, que visitaron el museo en el siglo XIX, hasta Picasso, Matisse, Dalí, Francis Bacon y Antonio Saura, quien decía: «Este museo no es el más extenso, pero sí el más intenso».
Las escuelas pictóricas de España, Flandes e Italia (sobre todo Venecia) ostentan el protagonismo en el Prado, seguidas por elfondo francés, más limitado si bien incluye buenos ejemplos de Nicolas Poussin y Claudio de Lorena. La pintura alemana cuenta con un repertorio discontinuo, con cuatro obras de Durero y múltiples retratos de Mengs como principales tesoros. Junto al breve repertorio de pintura británica, circunscrito casi al género del retrato, hay que mencionar la pintura holandesa, una sección no demasiado amplia pero que incluye a Rembrandt.
Aunque sean aspectos menos conocidos, el museo cuenta también con una importante sección de Artes decorativas (Tesoro del Delfín) y con una colección de esculturas, en la que destacan las greco-romanas.
Junto con el Museo Thyssen-Bornemisza y el Museo Nacional Centro de Arte Reina Sofía, el Museo Nacional del Prado forma elTriángulo del Arte, meca de numerosos turistas de todo el mundo. Esta área se enriquece con otras instituciones cercanas: elMuseo Arqueológico Nacional, el Museo Nacional de Artes Decorativas, la Real Academia de Bellas Artes de San Fernando y otros pequeños museos.',
 'http://upload.wikimedia.org/wikipedia/commons/9/94/Logo_del_Museo_Nacional_del_Prado.png'),
  (NULL,'Museo Van Gogh','Amsterdam,P.O Box 75366 NL ',52.3702157,4.895167899999933,'+31 (0)205705200','','','','','','',0,0,
 'El Museo van Gogh es una pinacoteca ubicada en Ámsterdam, Países Bajos, que alberga la colección de obras del pintor holandés Vincent van Gogh.El museo posee más de 200 pinturas de Vincent van Gogh, de todos sus periodos de creación, y unos 400 dibujos. 
Al morir Vincent van Gogh, a la edad de 37 años, dejó el extenso legado de su obra, de aproximadamente 900 pinturas y unos 1.100 dibujos. De éstos había logrado vender pocos y regalado algunos a sus amistades. Sus bienes fueron heredados por su hermano menor, el comerciante de arte Theo van Gogh. Éste había coleccionado, además de las obras de su hermano Vincent, otras de los artistas Paul Gauguin, Henri de Toulouse-Lautrec, Léon Lhermitte y Jean-François Millet. Lamentablemente Theo murió un año después de Vincent, por lo que la herencia fue administrada por su viuda Johanna van Gogh. Ella reemigró a los Países Bajos, donde organizó las primeras exhibiciones con las obras de Vincent van Gogh y contribuyó fundamentalmente a la difusión y el conocimiento público del artista. 
En 1905 tuvo lugar la primera gran exposición, en el Stedelijk Museum en Ámsterdam, mientras que el Rijksmuseum se negó a aceptar obras de Vincent en préstamo. Debido a que Vincent hizo varias versiones del mismo tema, Johanna van Gogh pudo vender algunas pinturas de la colección, sin dar la impresión general de reducirla. Johanna van Gogh promovió también tempranamente la publicación de las cartas de su marido en varios idiomas. Después de la muerte de Johanna van Gogh, el hijo, el ingeniero Vincent Willem van Gogh (1890-1978), heredó la colección. Él puso la colección a disposición de varios museos en calidad de préstamo, hasta que en 1960 creó la Fundación Vincent Van Gogh, a la que encomendó la colección. Las pinturas se exhibieron en exposición permanente en el Stedelijk Museum, hasta que en 1973 el Museo van Gogh abrió sus puertas.',
 'http://www.vangoghmuseum.nl/vgm/style/images/vgm_logo_geel.png'),
 
 -- 10
(NULL, 'Museo de Arte Moderno de Nueva York', 'Nueva York,11 W 53rd St', 40.7614029, -73.9776248, '+1 2127089400', '', '', '', '', '', '', 0, 0, 
'El Museo de Arte Moderno de Nueva York (llamado también MoMA, siglas en inglés de Museum of Modern Art) es un museo de arte situado en Manhattan en el 11 West con la calle 53 de Nueva York. El Museo de Arte Moderno de Nueva York abrió sus puertas al público el 7 de noviembre de 1929, y fue fundado por los filántropos estadounidenses Lillie P. Bliss, Mary Quinn Sullivan y Abby Aldrich Rockefeller para "ayudar a la gente a entender, utilizar y disfrutar de las artes visuales de nuestro tiempo". Es uno de los mejores museos de arte moderno del mundo.
El Museo se fundó como entidad privada, beneficiándose de numerosas donaciones de sus miembros y de empresas, siendo un ejemplo para otros museos de su clase, ampliando las fronteras del arte a disciplinas no admitidas en otras galerías.
Es considerado uno de los santuarios del arte moderno y contemporáneo del mundo, constituyendo (a juicio de muchos) una de las mejores colecciones de obras maestras. Alberga piezas tales como La noche estrellada de Van Gogh, Broadway Boogie Wogie de Piet Mondrian, Las señoritas de Avignon (1906) de Pablo Picasso, La persistencia de la memoria de Salvador Dalí y obras de artistas norteamericanos de primera fila como Jackson Pollock, Andy Warhol y Edward Hopper. El MoMA posee además importantes colecciones de diseño gráfico, diseño industrial, fotografía, arquitectura, cine e impresos.
Cuando el Museo de Arte Moderno comenzó a exponer sus obras, gran parte del público de aquella época despreciaba el cubismo y el arte abstracto, porque chocaban con las líneas directrices que hasta ese momento marcaban la pauta del "verdadero arte".
De las primeras vanguardias del siglo XX, el MoMA conserva obras clave de Pablo Picasso, Marc Chagall, Kandinsky, Mondrian, Henri Matisse, etc. Tiene un Jardín de Esculturas con obras Auguste Rodin, Alexander Calder, Louise Nevelson, Pablo Serrano y Aristide Maillol, además de una sala de cine.
Después de cuatro años de reformas, en 2004 fue inaugurado el nuevo MoMA, con casi el doble de espacio. El museo tiene dos restaurantes y una cafetería. Este museo está abierto de sábado a jueves desde las 10:30 hasta las 17:30 horas; los viernes, hasta las 20 horas. Está cerrado al público los días de Acción de gracias y Navidad.
En 2012 ha sido el primer museo del mundo en adquirir el código fuente de videojuegos al considerarlos arte.', 
'http://blog.newyorkpalace.com/wp-content/uploads/2013/05/moma-logo.gif');
 

-- Autors
INSERT INTO `e_autors` VALUES
-- id, nom, valoracio, num_valoracio, descripcio, imatge
-- 1
(NULL, 'Hans Haacke', 0, 0, 
'Hans Haacke (Colonia, 1936) es considerado pionero de la llamada crítica institucional, vertiente del arte conceptual, surgida a finales de los años sesenta. Formado y residente en los Estados Unidos, su obra transita de un puro conceptualismo inicial hacia un discurso crítico. Sus obras cuestionan los mecanismos y funciones de las instituciones culturales, políticas y económicas, que manifiestan ser herramientas activas en la construcción y transmisión de valores identitarios e ideológicos favorables al discurso y expansión de la globalización. Construye sistemas de relación mediante elementos literales tomados del cotidiano, cuyo significado crítico emerge por colisión simbólica al ser yuxtapuestos, procurando, más que denunciar, dejar ver la relación entre arte y comportamiento social.
La presente exposición se divide en dos ámbitos: una muestra de obras anteriores del artista, análisis y reflexiones sobre mercado y globalización, en que las instituciones contribuyen a alterar el valor económico del arte, neutralizando su potencial subversivo como The Invisible Hand of the Market (2009); la relación entre arte, patrocinio y publicidad en la pretensión de adquirir imágenes corporativas respetables en Thank you Payne Webber (1979), Global Marketing (1986-2011) o Helmsboro Country (1990); o lo espurio del discurso institucional, que percibe el arte como lubricante social para la aceptación de las actuales dinámicas económico-políticas descrito en On social Grease (1975) o Broken R.M... (1986). El proyecto Castillos en el aire (2012), concebido específicamente para el Museo Reina Sofía completa la muestra.
Castillos en el aire (2012), tiene en cuenta la realidad de un barrio del extrarradio madrileño, el Ensanche de Vallecas, donde Haacke encuentra las imágenes de las ruinas que corresponden a nuestra sociedad contemporánea. Junto a las escrituras inmobiliarias de hipotecas, planos, edificios, calles vacías, destaca los nombres de las mismas, dedicados a los principales movimientos artísticos del siglo XX.', 
'http://www.stiftungbremerbildhauerpreis.de/uploads/pics/Hans_Haacke_sw_01.jpg'),
-- 2
(NULL, 'Joan Miró', 0, 0, 
'Joan Miró i Ferrà (Barcelona, 20 de abril de 1893 — Palma de Mallorca, 25 de diciembre de 1983) pintor, escultor, grabador yceramista español, considerado uno de los máximos representantes del surrealismo. En su obra reflejó su interés en el subconsciente, en lo "infantil" y en su país. En un principio mostró fuertes influencias fauves, cubistas y expresionistas, pasando a una pintura plana con cierto aire naïf, como lo es su conocido cuadro La Masía del año 1920. A partir de su estancia en París, su obra se vuelve más onírica, coincidiendo con los puntos del surrealismo e incorporándose a este movimiento.En numerosas entrevistas y escritos que datan de la década de 1930, Miró manifestó su deseo de abandonar los métodos convencionales de pintura, en sus propias palabras de "matarlos, asesinarlos o violarlos", para poder favorecer una forma de expresión que fuese contemporánea, y no querer doblegarse a sus exigencias y a su estética ni siquiera con sus compromisos hacia los surrealistas.
Uno de sus grandes proyectos fue la creación en 1975, de la Fundación Joan Miró, ubicada en Barcelona, centro cultural y artístico para difundir las nuevas tendencia del arte contemporáneo, constituyéndose con un gran fondo de obras donadas por el autor; otros lugares con importantes fondos de sus obras son la Fundación Pilar i Joan Miró de Palma de Mallorca, el Museo Reina Sofía de Madrid, el Centro Pompidou de París (Musée National d''Art Moderne) y el MOMA de Nueva York.',
'http://www.biografias-discografias.com/joan+miro.jpg'),
-- 3
(NULL, 'Salvador Dalí i Domènech', 0, 0, 
'Salvador Felipe Jacinto Dalí i Domènech, marqués de Dalí de Púbol (Figueras, 11 de mayo de 1904 – ibídem, 23 de enerode 1989), fue un pintor, escultor, grabador, escenógrafo y escritor español, considerado uno de los máximos representantes delsurrealismo.
Dalí es conocido por sus impactantes y oníricas imágenes surrealistas. Sus habilidades pictóricas se suelen atribuir a la influencia y admiración por el arte renacentista. También fue un experto dibujante.Los recursos plásticos dalinianos también abordaron el cine, la escultura y la fotografía, lo cual le condujo a numerosas colaboraciones con otros artistas audiovisuales. Tuvo la habilidad de forjar un estilo marcadamente personal y reconocible, que en realidad era muy ecléctico y que «vampirizó» innovaciones ajenas. Una de sus obras más célebres es La persistencia de la memoria, el famoso cuadro de los «relojes blandos», realizado en 1931.
Como artista extremadamente imaginativo, manifestó una notable tendencia al narcisismo y la megalomanía, cuyo objeto era atraer la atención pública. Esta conducta irritaba a quienes apreciaban su arte y justificaba a sus críticos, que rechazaban sus conductas excéntricas como un reclamo publicitario ocasionalmente más llamativo que su producción artística.4Dalí atribuía su «amor por todo lo que es dorado y resulta excesivo, su pasión por el lujo y su amor por la moda oriental» a un autoproclamado «linaje arábigo», que remontaba sus raíces a los tiempos de la dominación árabe de la península ibérica.',
'http://www.ecured.cu/images/thumb/1/18/Salvador_Dal%C3%AD.jpg/260px-Salvador_Dal%C3%AD.jpg'),
-- 4
(NULL, 'Pablo Picasso', 0, 0, 
'(Pablo Ruiz Picasso, Málaga, 1881 - Moulins, Francia, 1973) Artista español. Hijo del también artista José Ruiz Blasco, en 1895 se trasladó con su familia a Barcelona, donde el joven pintor se rodeó de un grupo de artistas y literatos, entre los que cabe citar a los pintores Ramón Casas y Santiago Rusiñol, con quienes acostumbraba reunirse en el bar Els Quatre Gats.
Entre 1901 y 1904 Pablo Picasso alternó su residencia entre Madrid, Barcelona y París, mientras su pintura entró en la etapa denominada período azul, fuertemente influida por el simbolismo. En la primavera de 1904, Picasso decidió trasladarse definitivamente a París y establecerse en un estudio en las riberas del Sena. En la capital francesa trabó amistad, entre otros, con los poetas Guillaume Apollinaire y Max Jacob y el dramaturgo André Salmon; entre tanto, su pintura experimentó una nueva evolución, caracterizada por una paleta cromática tendente a los colores tierra y rosa. Al poco de llegar a París entró en contacto con personalidades periféricas del mundillo artístico y bohemio, como los estadounidenses Leo y Gertrude Stein, o el que sería su marchante por siempre, Daniel-Henry Kahnweiler.
Hacia finales de 1906 Pablo Picasso empezó a trabajar en una composición de gran formato que iba a cambiar el curso del arte del siglo XX: Les demoiselles d''Avignon. En esta obra cumbre confluyeron numerosas influencias, entre las que cabe citar como principales el arte africano e ibérico y elementos tomados del Greco y Cézanne. Bajo la constante influencia de este último, y en compañía de otro joven pintor, Georges Braque, Pablo Picasso se adentró en una revisión de buena parte de la herencia plástica vigente desde el Renacimiento, especialmente en el ámbito de la representación pictórica del volumen: fue el inicio del cubismo.
A partir de 1909, Picasso y Braque desarrollaron dicho estilo en una primera fase denominada analítica. En 1912 introdujeron un elemento de flexibilidad en forma de recortes de papel y otros materiales directamente aplicados sobre el lienzo, técnica que denominaron collage. La admisión en el exclusivo círculo del cubismo del pintor español Juan Gris desembocó en la etapa sintética de dicho estilo, marcado por una gama cromática más rica y la multiplicidad matérica y referencial.
Entre 1915 y mediados de la década de 1920 Picasso fue abandonando los rigores del cubismo para adentrarse en una nueva etapa figurativista, en el marco de un reencuentro entre clasicismo y el creciente influjo de lo que el artista denominó sus «orígenes mediterráneos». Casado desde 1919 con la bailarina rusa Olga Koklova y padre ya de un hijo, Paulo, Pablo Picasso empezó a interesarse por la escultura a raíz de su encuentro en 1928 con el artista catalán Julio González; entre ambos introdujeron importantes innovaciones, como el empleo de hierro forjado.
En 1935 nacería una hija, Maya, de una nueva relación sentimental, Marie-Therèse, con quien Pablo Picasso convivió abiertamente a pesar de seguir casado con Olga Koklova; a partir de 1936, ambas debieron compartir al pintor con una tercera mujer, la fotógrafa Dora Maar.
El estallido de la guerra civil española lo empujó a una mayor concienciación política, fruto de la cual es una de sus obras más conocidas, el mural de gran tamaño Gernika. En 1943 conoció a Françoise Gilot, con la que tendría dos hijos, Claude y Paloma. Tres años más tarde Pablo Picasso abandonó París para instalarse en Antibes, donde incorporó la cerámica a sus soportes predilectos.
En la década de 1950 realizó numerosas series sobre grandes obras clásicas de la pintura, que reinterpretó a modo de homenaje. En 1961 Pablo Picasso contrajo segundas nupcias con Jacqueline Roque; sería su última relación sentimental de importancia. Convertido ya en una leyenda en vida y en el epítome de la vanguardia, el artista y Jacqueline se retiraron al castillo de Vouvenargues, donde el creador continuó trabajando incansablemente hasta el día de su muerte.', 
'http://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/192px-Pablo_picasso_1.jpg'),
-- 5
(NULL, 'Leonardo Da Vinci',0,0,
'Leonardo da Vinci (Leonardo di ser Piero da Vinci) fue un pintor florentino. Notable polímata del Renacimiento italiano (a la vez anatomista, arquitecto, artista, botánico, científico, escritor, escultor, filósofo, ingeniero, inventor, músico, poeta y urbanista) nació en Vinci el 15 de abril de 1452 y falleció en Amboise el 2 de mayo de 1519, a los 67 años, acompañado de su fiel Francesco Melzi, a quien legó sus proyectos, diseños y pinturas.Tras pasar su infancia en su ciudad natal, Leonardo estudió con el célebre pintor florentino Andrea de Verrocchio. Sus primeros trabajos de importancia fueron creados en Milán al servicio del duque Ludovico Sforza. Trabajó a continuación en Roma, Bolonia y Venecia, y pasó los últimos años de su vida en Francia, por invitación del rey Francisco I.
Frecuentemente descrito como un arquetipo y símbolo del hombre del Renacimiento, genio universal, además de filósofo humanista cuya curiosidad infinita solo puede ser equiparable a su capacidad inventiva, Leonardo da Vinci es considerado como uno de los más grandes pintores de todos los tiempos y, probablemente, es la persona con el mayor número de talentos en múltiples disciplinas que jamás ha existido.Como ingeniero e inventor, Leonardo desarrolló ideas muy adelantadas a su tiempo, tales como el helicóptero, el carro de combate, el submarino y el automóvil. Muy pocos de sus proyectos llegaron a construirse (entre ellos la máquina para medir el límite elástico de un cable),puesto que la mayoría no eran realizables durante esa época. Como científico, Leonardo da Vinci hizo progresar mucho el conocimiento en las áreas de anatomía, la ingeniería civil, la óptica y la hidrodinámica.
Su asociación histórica más famosa es la pintura, siendo dos de sus obras más célebres, La Gioconda y La Última Cena, copiadas y parodiadas en varias ocasiones, al igual que su dibujo del Hombre de Vitruvio, que llegaría a ser retomado en numerosos trabajos derivados. No obstante, únicamente se conocen unas veinte de sus obras, debido principalmente a sus constantes (y a veces desastrosos) experimentos con nuevas técnicas y a su inconstancia crónica.Este reducido número de creaciones, junto con sus cuadernos que contienen dibujos, diagramas científicos y reflexiones sobre la naturaleza de la pintura, constituyen un legado para las sucesivas generaciones de artistas, llegando a ser igualado únicamente por Miguel Ángel.',
'http://arquitecturaycristianismo.files.wordpress.com/2014/02/davinci1.jpg'),
-- 6
(NULL,'Vicent Van Gogh',0,0,
'Vincent Willem van Gogh (Zundert, Países Bajos, 30 de marzo de1853-Auvers-sur-Oise, Francia, 29 de julio de 1890) fue un pintor neerlandés, uno de los principales exponentes delpostimpresionismo.
Pintó unos 900 cuadros (entre ellos 27 autorretratos y 148 acuarelas) y realizó más de 1.600 dibujos. Una figura central en su vida fue su hermano menor Theo, quien le prestó apoyo financiero de manera continua y desinteresada. La gran amistad entre ellos está documentada en las numerosas cartas que se intercambiaron desde agosto de 1872. De las 800 cartas que se conservan del pintor, unas 650 eran para Theo; las otras son correspondencia con amigos y familiares.
A pesar que desde muy joven tuvo inclinación hacia el dibujo, su primer trabajo fue en una galería de arte. Más tarde se convirtió en pastor protestante y en 1879, a la edad de 26 años, se marchó como misionero a una región minera de Bélgica, donde comenzó a dibujar a la gente de la comunidad local. En 1885 pintó su primera gran obra Los comedores de patatas. En ese momento su paleta se componía principalmente de tonos sombríos terrosos. La luz de colores vivos por la que es conocido surgió en obras posteriores, cuando se trasladó al sur de Francia, consiguiendo su plenitud durante su estancia en Arlés en 1888. La calidad de su obra sólo fue reconocida después de su muerte, considerándose en la actualidad uno de los grandes maestros de la pintura. Tuvo una gran influencia en el arte del siglo XX, especialmente entre los expresionistas alemanes y los fauvistas comoDerain, Vlaminck y Kees Van Dongen.Sufrió frecuentes brotes de una enfermedad mental a lo largo de su vida, que le llevó a producirse una herida de bala que acabó con su vida a la edad de 37 años. A pesar de que existe una tendencia general a especular que su enfermedad mental influyese en su pintura, el crítico de arte Robert Hughes cree que las obras del artista están ejecutadas con un completo control.',
'http://wondrus.la/wp-content/uploads/2013/03/Vincent-Van-Gogh-9515695-3-402.jpg'),
-- 7
(NULL,'Maestro Tahull',0,0,
'El Maestro de Tahull, considerado como el más grande de los pintores de murales del siglo XII en Cataluña (España) y también como el más importante de los pintores románicos de Europa. Su principal obra son las pinturas murales del ábside la de la iglesia de San Clemente de Tahull.
Se considera casi perfecta su manera de articular los espacios. Dibuja los rostros de las figuras con gran realismo y estilización. Utiliza en su gama cromática los colores carmín, azul y blanco. Se ha llegado a pensar que trajo consigo desde Italia, además de las herramientas, los materiales necesarios para su trabajo.
En 1123 el obispo Ramón de Roda consagró la iglesia de Tahull y es muy probable que entrara en contacto con este maestro, encargándole entonces la decoración del pequeño ábside de la catedral de Roda de Isábena en Huesca.
Las pinturas de la capilla mayor de Santa María de Tahull tienen bastante afinidad con las de san Clemente; el artista debía ser del círculo del Maestro de Tahull, aunque su trabajo es menos genial y con una gama cromática menos rica en en matices.',
'http://lh6.ggpht.com/_of1CZg78E7o/Su_SZ8z_UxI/AAAAAAAAGok/DTZnYU3vMnc/s512/AntoniCacig%C3%B3ssept09.jpg');



-- Obres
INSERT INTO `e_obres` VALUES
-- id, nom, mid, aid, valoracio, num_valoracions, descripcio, imatge
(NULL, 'Ciència i caritat', 1, 4, 0, 0, 
'Con “Ciencia y Caridad al descubierto” iniciamos una serie de muestras o displaysque ofrecerán una visión profunda e inédita de obras de la colección.
Inicia esta nueva línea del museo Ciencia y Caridad (1897), una de las obras más emblemáticas de la colección y la más representativa del periodo de formación del joven Picasso. El óleo Ciencia y Caridad representa la culminación del proceso formativo del artista, dentro del marco académico y oficial de la España decimonónica y, a la vez, el punto de ruptura de la influencia paterna sobre el joven pintor. Acompañada de una selección de obras de otros artistas, de documentación de época y del resultado de los últimos estudios de pigmento y composición realizados por el museo, esta obra se muestra como nunca hasta ahora se había podido ver.
La muestra se sitúa en las salas 3 y 4 del museo respetando la habitual ubicación de la obra. Ahora la podemos ver contextualizada, rodeada de pinturas de otros artistas que, como Picasso, representaron la visita del médico dentro de la corriente del realismo social.
En la investigación que hemos realizado nos ha sorprendido encontrar tantas pinturas con un tema y un tratamiento tan cercanos a los de nuestro óleo. Y hemos seleccionado aquellas que más se ajustaban a nuestra tesis y a la idea de exposición de pequeño formato. Uno de los momentos más satisfactorios en el proceso de investigación fue encontrar la papeleta de inscripción a la Exposición Nacional de Bellas Artes de 1897, y exponerla junto a los bocetos de la obra.
En la exposición se presentan también los resultados de una investigación en profundidad de la obra mediante radiografías, gigafotografías y análisis de pigmentos.
Las gigafotografías permiten un acercamiento a la obra para observar las pinceladas casi con más detalle que al natural, y nos dejan apreciar de manera sorprendente el trabajo del artista. El análisis de pigmentos también ha sido revelador. Visualmente resulta una tela con colores tenues y repetitivos, pero el análisis nos ha descubierto que Picasso usó una paleta rica, de 16 colores, para conseguir las tonalidades deseadas. Las dudas compositivas de la artista se ponen también de manifiesto en la radiografía.',
 'http://www.bcn.cat/museupicasso/imatges/lacoleccio/highlights/mpb110-046.jpg'),	
(NULL, 'Condensation Cube', 5, 1, 0, 0, 
'Cubo de condensación (1965) es una de las obras iniciales en la trayectoria artística de Hans Haacke. Si con el tiempo este artista desarrolló una crítica al arte entendido como institución y sistema, sus primeras obras se centran en el arte en el sentido de proceso y sistema físico. Interesado en la biología, la ecología y la cibernética, a mediados de los años sesenta, Hans Haacke accedió a los textos de Ludwig von Bertalanffy, especialmente a su ensayo de 1968, Teoría general de los sistemas. Para este biólogo y filósofo austríaco, un organismo vivo es un sistema abierto que cambia continuamente en función de su diálogo o interacción con el entorno. Las primeras obras de Haacke, como Cubo de condensación, son una transposición de este concepto al ámbito del arte.
En el año 1962, Haacke empezó a producir obras que incorporan contenedores de plexiglás llenos de agua. Cubo de condensación es un caso paradigmático de su interés por procesos físicos tan básicos como la condensación y la evaporación del agua. La obra consiste en un cubo transparente de metacrilato que contiene agua. Debido a la diferencia de temperatura entre el interior y el exterior, el agua se condensa formando vapor y gotas que se desplazan por las paredes del cubo y adoptan distintas formas. Esta pieza resume el interés de Haacke por los sistemas físicos cerrados, el crecimiento biológico y los movimientos aleatorios, mientras que pone el acento en una idea del arte que ha perdido su capacidad representativa y referencial para revelarse como un hecho o estado de las cosas. El propio Haacke lo explicó: "Las condiciones son comparables a un organismo vivo que reacciona de forma flexible a su entorno. La imagen de la condensación no puede preverse con precisión. Cambia libremente, determinada únicamente por límites estadísticos. Me gusta esta libertad" (Nueva York, octubre de 1965).
Un proceso físico tan básico como la condensación del agua le sirve a Haacke para redefinir la obra de arte como un sistema vivo y, de forma muy significativa, el papel del espectador o usuario del arte. Si bien la formación d agua dentro del cubo tiene que ver con las condiciones del entorno inmediato, la misma presencia humana también forma parte de este entorno. La obra de arte depende de la presencia física del espectador en el espacio circundante y este modifica la obra sin querer. Es así como Haacke incorpora al espectador en el arte de una forma muy innovadora, como cuerpo físico.',
 'http://www.macba.cat/uploads/20131213/1523_250x.jpg'),
(NULL,'El Ábside de San Clemente de Tahull',6,7,0,0,
'El Ábside de San Clemente de Tahull es una pintura románica perteneciente al conjunto de la decoración mural de la iglesia de San Clemente de Tahull en el Valle de Bohí, donde se encuentra la mayor concentración de arte románico de toda Europa, con una iglesia por cada 25 km².1 Actualmente se expone en el Museo Nacional de Arte de Cataluña.

Esta es una de las obras maestras del románico europeo. Su genialidad reside en la combinación de elementos de diferentes visiones bíblicas –las del Apocalipsis, Isaías y Ezequiel– para presentarnos al Cristo del Juicio Final. Éste aparece desde el fondo provocando un movimiento centrífugo de la composición, en la que domina el sentido ornamental de los perfiles y la habilidad en la utilización del color para dar volúmenes. Por su excepcionalidad y fuerza pictórica, la obra del Maestro de Tahull se ha proyectado a la modernidad y ha fascinado a artistas de las vanguardias del siglo XX, como Picasso o Francis Picabia.

La pintura mural del ábside central de la iglesia de San Clemente de Tahull, forma parte del conjunto pictórico que comprende también la decoración de los arcos triunfales, la del ábside lateral, la inscripción de consagración y una ventana anterior. Hay más pintura "in situ".

Pintura original "in situ" representando a san Clemente.
La cronología de las pinturas toma como referencia la inscripción pintada que se ha conservado sobre una columna del lado del Evangelio, la mencionada inscripción nombra la consagración de la iglesia en el año 1123 y presenta los caracteres del mismo tipo que en las diferentes inscripciones de las pinturas del ábside.

La obra del ábside al servicio del tema religioso y su significado, está representada a través de medios antinaturalista y de abstracción, con rasgos simplificados y cambios hacia la modelación geométrica de las formas naturales humanas, fue también una de las características comunes del arte románico. Se trata de una Maiestas Domini o Pantocrátor, la epifanía del Dios legislador, todopoderoso, que viene a juzgar el pueblo.',
'http://images.artelista.com/artelista/obras/big/9/3/5/4937156295017011.jpg'),
(NULL,'El dormitorio de Arlés',9,6,0,0,
'El dormitorio en Arlés (en francés: La Chambre à Arles; en neerlandés: Slaapkamer te Arles) es el título que reciben tres cuadros similares, obra del pintor del siglo XIX holandés postimpresionista Vincent van Gogh.
El título que Van Gogh le dio a esta composición fue simple: El dormitorio (en francés: La Chambre à coucher). Hay tres versiones auténticas descritas en sus cartas, que se distinguen con facilidad entre ellas por los cuadros que hay a la derecha de la pintura.
El cuadro representa el dormitorio de Van Gogh en el número 2 de la Place Lamartine en Arlés, Bocas del Ródano, Francia, conocida como la Casa Amarilla. Era la primera habitación propia que tenía Van Gogh.1 En ella estuvo en 1888-1889. Lo pintó antes de la llegada a Arlés de Paul Gaugin, amigo del artista: el encuentro habría hecho nacer luego un círculo artístico.
La puerta a la derecha se abría a la planta superior y la escalera, la puerta de la izquierda servía para la habitación de invitados que preparó para Gauguin. Sobre la pared del frente se abre una ventana, por encima de una mesita, ligeramente descentrada. Esta ventana daba a la Place Lamartine y sus jardines públicos. Pero el panorama más allá de la ventana no puede verse
La habitación no era rectangular sino trapezoidal, con un ángulo obtuso en la esquina izquierda de la pared frontal y un ángulo agudo en la derecha.2 Van Gogh evidentemente no dedicó mucho tiempo a este problema, simplemente indicó que allí, de alguna manera, había una esquina.
Es un alojamiento modesto, con poco mobiliario, hecho de madera de pino: una cama a la derecha, un perchero, dos sillas, una mesilla de madera en el ángulo y cuadros en las paredes.1
Una fuerte perspectiva, con la típica leve torsión, propia del autor, refleja sus ideas sobre la pintura.',
'http://cv.uoc.edu/~04_999_01_u07/percepcions/arle1.gif'),
(NULL,'El gran masturbador',7,3,0,0,
'El gran masturbador es un famoso cuadro del pintor español Salvador Dalí pintado en 1929. Está hecho mediante la técnica del óleo sobre lienzo, es de estilo surrealista y sus medidas son 110 x 150 cm. Se conserva en Madrid, en el Museo Reina Sofía pues fue legado por Dalí a España.
Este cuadro tiene las características de toda su pintura surrealista y posee una unidad equilibrada a pesar del gran número de elementos que presenta. Refleja el malestar del autor que temía, incluso, perder la cordura. Tanto el título, como el motivo central no dejan dudas sobre las implicaciones sexuales del cuadro; el sexo era una de las obsesiones del pintor.
En la pintura están retratadas todas las obsesiones del autor:
El elemento principal es un busto antropomórfico, mezcla de cabeza humana y rocas de la costa Brava de los alrededores deCadaqués, que repetirá en muchos otros cuadros como La persistencia de la memoria y El enigma del deseo. Estilizado pero reconocible, se caracacteriza por su color amarillento, su gran nariz apoyada en el suelo y su cara alargada. Las pestañas largas representan la contraposición entre el sueño anodino de una consumación física irremediable y el sueño de que nuestros deseos se cumplan.
La langosta, un animal que le provocaba terror desde su infancia y que se encuentra pegado a la boca de su autorretrato. Está en estado de descomposición, lo que atrae muchas hormigas que simbolizan la muerte.
Un anzuelo como atadura a su familia que quería retenerle a su lado y volver a un modo de vida tradicional del que él da muestras de querer desprenderse definitivamente.
El león como deseo sexual, con una lengua rosada como símbolo fálico.
Unas piedras como su pasado.
Una figura aislada como soledad.
El tema de la masturbación aparece en la mujer que emerge de su retrato y cuyo rostro está cerca de unos genitales masculinos escondidos en unos ceñidos calzoncillos.
Un lirio pegado a la mujer que simboliza la pureza, una enrevesada forma de definir a la masturbación como la relación sexual más pura. El pistilo de la flor es, además, otro símbolo fálico.
Como es normal desde que la conoció, Gala aparece representada, en este caso en la pareja que se abraza, donde ella se metamorfosea en una roca, recuerdo de los paseos que dieron por la playa.',
'http://www.museoreinasofia.es/sites/default/files/obras/AS11140.jpg'),
(NULL,'Guernica',7,4,0,0,
'Guernica es un famoso cuadro de Pablo Picasso, pintado en los meses de mayo y junio de 1937, cuyo título alude al bombardeo de Guernica, ocurrido el 26 de abril de dicho año, durante la Guerra Civil Española. Fue realizado por encargo del Director General de Bellas Artes, Josep Renau a petición del Gobierno de la República Española para ser expuesto en el pabellón español durante la Exposición Internacional de 1937 en París, con el fin de atraer la atención del público hacia la causa republicana en plena Guerra Civil Española.
En la década de 1940, puesto que en España se había instaurado la dictadura militar del general Franco, Picasso optó por dejar que el cuadro fuese custodiado por el Museo de Arte Moderno de Nueva York, aunque expresó su voluntad de que fuera devuelto a España cuando volviese al país la democracia. En 1981 la obra llegó finalmente a España. Se expuso al público primero en el Casón del Buen Retiro, y luego, desde 1992, en el Museo Reina Sofía de Madrid, donde se encuentra en exhibición permanente.
Su interpretación es objeto de polémica, pero su valor artístico está fuera de discusión. No sólo es considerado una de las obras más importantes del arte del siglo XX, sino que se ha convertido en un auténtico "icono del siglo XX", símbolo de los terribles sufrimientos que la guerra inflige a los seres humanos.
El Guernica es un óleo sobre lienzo, con unas dimensiones de 3,50 x 7,80 m.1 A pesar de su título, y de las circunstancias en que fue realizado, no hay en él ninguna referencia concreta al bombardeo de Guernica ni a la Guerra Civil Española.2 No es, por lo tanto, un cuadro narrativo, sino simbólico.3 Está pintado utilizando únicamente el blanco y negro, y una variada gama de grises.
La estructura del cuadro es semejante a la de un tríptico, cuyo panel central está ocupado por el caballo agonizante y la mujer portadora de la lámpara.4 Los laterales serían, a la derecha, la casa en llamas con la mujer gritando, y, a la izquierda, el toro y la mujer con su hijo muerto. El del tríptico no es, sin embargo, el único principio de ordenación espacial presente en el Guernica. Las figuras están organizadas en triángulos, de los cuales el más importante es el central, que tiene como base el cuerpo del guerrero muerto, y como vértice la lámpara.',
'http://3.bp.blogspot.com/-Es05FSCGh4Q/TjD_3eq_9BI/AAAAAAAAAHs/oGv_iAwzsgs/s1600/guernica.jpg'),
(NULL,'La Masia',4,2,0,0,
'La masía es una pintura al óleo, realizada por el pintor Joan Miró entre los años 1921 y 1922, constituye una especie de inventario de la masía que poseía su familia desde el año 1910 en la población de Montroig. El mismo Miró consideraba esta obra como una pieza clave en su carrera artística, describiénola como «un resumen de toda mi vida en el campo». Está conservada en la National Gallery of Art, Washington DC, donde fue donada por Mary Hemingway en 1987.

La masía, es la obra cumbre de su época «detallista», realizada a los veintinueve años de edad y que James J. Sweeney consideró como «obra clave del desarrollo posterior del artista».3 Trabajó en ella durante nueve meses de dura elaboración; la relación mítica mantenida por Miró con la tierra, se resume en este cuadro, en el grafismo de carácter ingenuo y realista de todos los objetos, los animales son los domésticos, los vegetales son los que el hombre trabaja y los objetos son todos de uso diario y necesarios para el hombre. Estudia todos los detalles al mínimo, es lo que se llama «caligrafía mironiana» empleada por el artista también en otras pinturas como Mont-roig, la iglesia y el pueblo (1919), Retrato de niña (1918) o Huerto con asno (1918), punto de partida todas ellas para los siguientes años de su contacto con el surrealismo.
En la pintura se nota la familiaridad que todo lo representado tenía con Miró. Está realizada como un escenario donde se pueden apreciar las actividades propias de una masía y las características del edificio, de los objetos y animales. La definición clara de los dibujos consigue hace fácil el reconocimiento de todo sin producir ninguna confusión.Como si fuese un inventario se muestra un mulo, un caballo, unas gallinas, un perro, una cabra, un conejo, caracoles, lagartijas e insectos, la mayoría aislados y muchos de ellos colocados sobre algún objeto que los hace aparecer como expuestos sobre unas penas, esta posibilidad de unión entre objeto y animal es la pieza que según Braque «asegura su justificación» y consigue el movimiento entre el resto de los elementos representados de la obra. El edificio de la casa incluye las grietas y los desconchones en el revoque de las paredes. En el centro de la pintura se encuentra un gran eucaliptus que nace de un círculo negro que contrasta con el círculo blanco del cielo que representa el sol.Todos los elementos de esta pintura, animales y objetos, llegaron a ser prototipos en forma de símbolo que fueron apareciendo en diversas obras realizadas por Miró, por ejemplo uno de los más habituales es la escalera de mano que representa la evasión.',
'http://cv.uoc.edu/~04_999_01_u07/percepcions/miro.jpg'),
(NULL,'Las Meninas',1,4,0,0,
'as Meninas es una serie de 58 cuadros que Pablo Picasso pintó en el año 1957 en la que realizó un análisis exhaustivo, reinterpretando y recreando varias veces Las Meninas de Diego Velázquez. La suite se conserva íntegramente en el Museo Picasso de Barcelona,1 es la única serie completa del artista que perdura junta. Se trata de un estudio de obra muy extenso, que consta de cuarenta y cinco interpretaciones de la obra, nueve escenas de un palomar, tres paisajes y un Retrato de Jacqueline.
El mismo Picasso entendía toda esta serie como un conjunto y como tal la donó al museo barcelonés en mayo de 1968, en memoria de Jaime Sabartés, fallecido el mismo año. Es famosa la frase de Picasso dicha a Sabartés en 1950:
Si alguien se pusiese a copiar Las Meninas, totalmente con buena fe, al llegar a cierto punto y si el que las copiara fuera yo, diría: ¿Y si pusiera esta un poquito más a la derecha o a la izquierda? Yo probaría de hacerlo a mi manera, olvidándome de Velázquez.La prueba me llevaría de seguro a modificar la luz o a cambiarla, con motivo de haber cambiado de lugar algún personaje. Así, poco a poco, iría pintando unas Meninas que serían detestables para el copista de oficio, pero serían mis Meninas.',
'http://upload.wikimedia.org/wikipedia/ca/e/e4/PabloPicasso_Meninas.jpg'),
(NULL,'La minotauromaquia',1,4,0,0,
'La Minotauromaquia es un aguafuerte realizado por Pablo Picasso en 1935 y que forma parte de la colección del Museo Picasso de Barcelona. Se trata de una donación del artista realizada en 1938, contiene una dedicatoria: «para el Museo de Arte Moderno. Picasso París, 30 de setembre de 1938»

El minotauro —criatura mitológica con cuerpo humano y cabeza de toro— es uno de los grandes protagonistas de la producción picassiana de los años treinta, tanto en pintura como en obra gráfica, y es el tema de este grabado fundamental de Picasso, La Minotauromaquia, considerado uno de los mejores del siglo XX.1
Es un aguafuerte con rascado, de factura perfecta, realizado en primavera de 1935e impreso por Roger Lacourière. Obra de difícil interpretación simbólica, es una síntesis de toda una serie de obras en torno al mito. Los personajes principales son una joven sosteniendo una vela y un ramo de flores, confrontando a la bestia con expresión serena; un gran minotauro en el centro de la composición; unamujer torera (que sugiere como modelo a Marie Thérèse Walter, con quien Picasso mantuvo una relación de años), herida, con los pechos descubiertos, desplomándose de la grupa de un caballo; en la parte izquierda, un hombre subido a una escalera, barbudo y medio desnudo, en actitud de huir; y en la parte superior, dos jóvenes mirando la escena desde una ventana, con palomas.1
La Minotauromaquia, realizada un año antes del inicio de la guerra civil española, está considerada como uno de los precedentes inmediatos del Guernica. En el MoMA (Museum of Modern Art) de Nueva York y en el Museo Picasso de París también se conservan ejemplares de La Minotauromaquia.',
'http://www.museoreinasofia.es/sites/default/files/obras/DE00052.jpg'),
(NULL,'La noche estrellada',10,6,0,0,
'La noche estrellada (en neerlandés De sterrennacht) es una obra maestra del pintor Post-impresionisionista Vincent van Gogh. El cuadro muestra la vista exterior durante la noche desde la ventana del cuarto del sanatorio de Saint-Rémy-de-Provence, donde se recluyó hacia el final de su vida. Sin embargo, la obra fue pintada durante el día, de memoria. Data de mediados de 1889, trece meses antes del suicidio de van Gogh. Desde 1941 forma parte de la colección permanente del Museo de Arte Moderno de Nueva York. Considerado como el magnum opus de van Gogh, el cuadro ha sido reproducido en numerosas ocasiones, siendo una de sus obras más conocidas. Ha usado óleo humedecido y pinceles finos.
La obra fue pintada en el año 1889, el mismo año que se arrancó el lóbulo de la oreja después de mantener una fuerte discusión con su amigo Gauguin, poco tiempo después regresó a su casa amarilla donde empezó a pintar de nuevo, más adelante ingresó en el hospital de Sanit-Rémy donde empezó a tener alucinaciones y ataques epilépticos, pero no recibió ningún tratamiento. Empezó a pintar en el jardín del hospital donde habian cipreses. Van Gogh se comportaba violento contra otras personas, llegó a intoxicarse al ingerir pintura, se sentía acosado por las alucinaciones y lo demuestra en la obra La noche estrellada.',
'http://www.artpostman.com/tienda/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/n/o/noche-estrellada-van-gogh.jpg'),
(NULL,'La persistencia de la memoria',2,3,0,0,
'La persistencia de la memoria, conocido también como Los relojes blandos es un famoso cuadro del pintor español Salvador Dalí pintado en 1931. Realizado mediante la técnica del óleo sobre lienzo, es de estilo surrealista y sus medidas son 24 x 33 cm. La pintura fue exhibida en la primera exposición individual de Dalí en la Galerie Pierre Colle de París,1 del 3 al 15 de junio de 1931, y en enero de 1932 en una exposición en la Julien Levy Gallery de Nueva York, Surrealism: Paintings, Drawings and Photographs.1 Se conserva en el MoMA (Museo de Arte Moderno) de Nueva York, donde llegó en 1934 como donativo de Helen Lansdowne Resor, magnate de la publicidad que posteriormente llegaría a ser patrona del museo; el precio pagado fue de 400 dólares.2 En una revisión posterior del cuadro, Dalí creó La desintegración de la persistencia de la memoria.
El cuadro fue cedido en préstamo por dos meses, del 16 de enero al 18 de marzo del 2009,2 al Teatro-Museo Dalí de Figueras, Gerona, siendo la primera vez que ha podido verse en España.
En el cuadro aparece la bahía de Port Lligat al amanecer. El paisaje es simple; aparece el mar al fondo y una pequeña formación rocosa a la derecha. La obra representa un paisaje onírico, de grandes espacios dilatados, en el que los elementos se asocian de forma insólita. En primer plano a la izquierda, se observa un bloque probablemente de madera, que hace las funciones de una mesa, sobre el que se disponen dos relojes y un árbol incompleto, con una sola rama y sin hojas. El reloj más grande es blando, tiene una mosca sobre él y cae, escurriéndose por el borde de la mesa. El pequeño, parece un reloj de bolsillo cerrado y las hormigas se mueven sobre él. Pende del árbol un tercer reloj, también blando. En el centro de la obra aparece una extraña figura que simula una cabeza blanda, cuyo cuello se diluye en la oscuridad. Llama la atención la enorme nariz, la especie de lengua que sale de ella y el ojo cerrado con largas pestañas. La figura parece dormir sobre la arena. El artista ha colocado sobre esta figura un cuarto reloj, igualmente blando y que también parece derretirse o escurrirse. Los elementos anteriormente descritos se ambientan en lo que parece una playa desierta, con el mar y una cala rodeada de acantilados al fondo. El cielo y el mar se confunden.',
'http://uploads5.wikipaintings.org/images/salvador-dali/the-persistence-of-memory-1931.jpg'),
(NULL,'La tentación de San Antonio',3,3,0,0,
'La tentación de San Antonio es un cuadro realizado por el pintor español Salvador Dalí en 1946. La obra está pintada al óleo sobre lienzo, es surrealista y mide 90 x 119,5 cm. Se conserva en Bruselas en el Musée Royaux des Beaux-Arts.

En el cuadro se muestra a san Antonio Abad en un desierto, arrodillado y sosteniendo una cruz hecha con dos varitas para protegerse de las tentaciones que lo atacan, con el antiguo gesto del exorcismo. Estas son representadas por un caballo y una fila de elefantes, todos estos con sus patas alargadas de forma grotesca y cada uno cargando con una tentación.

Exposición sobre Dalí en Londres. En primer término hay una escultura de un elefante de patas alargadas con una pirámide en el lomo, idéntico a uno de los que aparecen en el cuadro. Al fondo se encuentra el London Eye.
San Antonio es representado como un mendigo, está desnudo y despeinado y se apoya sobre una piedra. Delante de él hay una calavera.

El cuadro describe literalmente las tentaciones a las que el hombre normalmente cae:

Triunfo, representado con el caballo, el cual tiene sus pezuñas desgastadas y llenas de polvo. Este animal recuerda a los jumentos esqueléticos de los primeros cuadros surrealistas del autor.
Sexo, representado por la mujer sobre el primer elefante.
Oro y riquezas, representados por los dos elefantes sobre los que hay una pirámide y una casa de oro y dentro de esta última, un busto de mujer lo aguarda.
Más atrás, otro elefante carga un altísimo monolito sobre su espalda. Detrás de este y sobre las nubes, hay un castillo.

En el paisaje desértico, dos hombres discuten y al fondo, un hombre lleva de la mano a su hijo. Este último par de personajes también es representado en Vestigios atávicos después de la lluvia. Un ángel blanco vuela sobre el desierto.',
'http://gredossandiego.net/blogs/alcala/media/blogs/cristina/Dali%205.jpg?mtime=1384459449'),
(NULL,'La última cena',8,5,0,0,
'La última cena (en italiano: Il cenacolo o L’ultima cena) es una pintura mural original de Leonardo da Vinci ejecutada entre 1495 y 1497,se encuentra en la pared sobre la que se pintó originariamente, en el refectorio del convento dominico de Santa Maria delle Grazie en Milán (Italia).3 La pintura fue elaborada, para su patrón, el duque Ludovico Sforza de Milán. No es un fresco tradicional, sino un mural ejecutado al temple y óleo sobre dos capas de preparación de yeso extendidas sobre enlucido. Mide 460 cm de alto por 880 cm de ancho. Muchos expertos e historiadores del arte, consideran la La última cena como una de las mejores obras pictóricas del mundo.
La afirmación de Jesús «uno de vosotros me traicionará» causa consternación en los doce seguidores de Jesús, y ese es el momento que Leonardo representa, intentando reflejar "los movimientos del alma", las distintas reacciones individualizadas de cada uno de los doce apóstoles: unos se asombran, otros se levantan porque no han oído bien, otros se espantan y, finalmente, Judas retrocede al sentirse aludido.
La mesa con los trece personajes se enmarca en una arquitectura clásica representada con exactitud a través de la perspectiva lineal, concretamente central, de manera que parece ampliar el espacio del refectorio como si fuera un trampantojo salvo por la diferente altura del punto de vista y el monumental formato de las figuras. Ello se logra a través de la representación del pavimento, de la mesa, los tapices laterales, las tres ventanas del fondo o, en fin, los casetones del techo. Esta construcción en perspectiva es lo más destacado del cuadro.
La escena parece estar bañada por la luz de las tres ventanas del fondo, en las que se vislumbra un cielo crepuscular, de igual manera que por la luz que entraría a través de la ventana verdadera del refectorio. Dicha luminosidad, así como el fresco colorido, han quedado resaltados a través de la última restauración. Los 12 Apóstoles están distribuidos en cuatro grupos de 3. Ello sigue un esquema de tríadas platónicas, de acuerdo a la escuela florentina de Ficino y Mirandola. Analizando de izquierda a derecha, en la segunda tríada se encuentra Judas, cuya traición rompe la tríade, colocándole fuera de ella. La tercera tríada desarrolla la teoría del amor platónico. El amor es el deseo de la belleza, la esencia de Dios es amor y el alma va hacia su amor embriagada de belleza. En la cuarta tríada se observa a Platón, Ficino y quizá el propio Leonardo, trata del diálogo filosófico que lleva a la verdad de Cristo.
En la obra los discípulos y Jesús aparecen sentados y atrás de ellos se puede apreciar un paisaje como si fuera un bosque o incluso como si fuera el paraíso.Los apóstoles se agrupan en cuatro grupos de tres, dejando a Cristo relativamente aislado. De izquierda a derecha según las cabezas, son: Bartolomé, Santiago el Menor y Andrés en el primer grupo; en el segundo Judas Iscariote con pelo y barba negra, Simón Pedro y Juan, el único imberbe del grupo; Cristo en el centro; Tomás, Santiago el Mayor y Felipe, también sin barba en el tercer grupo; Mateo, aparentemente sin barba o con barba rala, Judas Tadeo y Simón el Celote en el último. Todas las identificaciones provienen de un manuscrito autógrafo de Leonardo hallado durante el siglo XIX.',
'http://tejiendoelmundo.files.wordpress.com/2011/09/la-ultima-cena1.jpg'),
(NULL,'Paisaje Catalán',10,2,0,0,
'Joan Miró (1893–1983) es uno de los más originales e icónicos maestros de la modernidad. A lo largo de su carrera, el artista catalán desarrolló un lenguaje surrealista de símbolos y colores que aún hoy sigue considerado como una de las grandes influencias del Expresionismo Abstracto.
Tras instalarse en el taller de Pau Gargallo en París, Miró formó parte del grupo de artistas que, liderados por André Breton, fundaron en 1924 el movimiento surrealista. Miró jamás siguió al pie de la letra los principios del surrealismo, pero gracias a él consiguó acabar con su breve y poco prometedora etapa “detallista”. Comparando su obra “La Masía” (1921-22) con otra de temática prácticamente idéntica, “Tierra labrada” (1923-24), se aprecia claramente la evolución del estilo del artista.
“Paisaje catalán” es ya un ejemplo claro del estilo surrealista de Joan Miró, que culminaría en el excelente “Carnaval del arlequín”, pintado un año después. Dos diferentes colores en el fondo hacen referencia al cielo y la tierra. En la parte izquierda de la pintura aparece la figura del cazador, con barretina y pipa, solo identificable si el espectador conoce obras como “Cabeza de campesino catalán” (Galería Nacional de Washington) o “Campesino catalán con guitarra” (Museo Thyssen). En la parte baja de la pintura aparece una raspa de sardina, a la que parecen hacer referencia las letras “sard” a su derecha.
“Paisaje catalán” tuvo una gran importancia en la carrera de Miró, influyendo en su serie de “paisajes imaginarios” (como ”Perro ladrando a la luna” o “Paisaje de la liebre”) realizados en 1926-27.',
'http://img.directoalpaladar.com/2008/07/paisaje%20catalan.jpg'),
(NULL,'Port Alguer',4,3,0,0,
'Obra realizada por el pintor Salvador Dalí en 1924.',
'http://www.salvador-dali.org/media/IMATGES/i0019.jpg'),
(NULL, 'Retrat de la tia Pepa', 1, 4, 0, 0,
 'Josefa Ruiz Blasco nacida en 1825 era la tía de Pablo Picasso y la mayor de losonce hermanos Ruiz Blasco. Vivió con sus dos hermanos Matilde y José (padre de Picasso) en la Plaza de la Merced de Málaga hasta que éste se casó y entonces ella se fue a vivir con su hermano pequeño Salvador. La muerte de Josefa coincidió con los días de la última visita de Picasso a Málaga, en 1901.
Josefa Ruiz era una mujer soltera, conocida por su fuerte genio, mal humor y extremada religiosidad y tenía una pierna paralizada. En casa de su hermano Salvador vivía en un ala apartada de la casa, de donde rara vez salía, y su habitación estaba repleta de santos, reliquias religiosas y recuerdos de su difunto hermano Pablo Ruiz Blasco. Picasso recibe Pablo como nombre de pila en recuerdo de su tío que murió dos años antes de que él naciera.
Pablo Picasso hizo algunas estancias veraniegas en Málaga con su familia y durante el verano de 1896, cuando tenía 15 años, realizó por encargo de su tío Salvador un retrato al óleo de Josefa Ruiz, considerado uno de los hitos retratístiques del joven Picasso. El artista juega con la luz del rostro y el tratamiento cromático consiguiendo profundizar en el perfil psicológico de su tía.
John Richardson explica el volumen I de Picasso. Una biografía que después de la primera negativa de su tía a hacerse el retrato, Josefa cambió de opinión y fue a buscar a Picasso vestida de domingo con una capa de invierno, una cofia de encaje que le había hecho su hermana y el reloj de oro de su hermano Pablo. Dice la leyenda que Picasso pintó el retrato en menos de una hora.
Según el biógrafo picassiano Josep Palau i Fabre el Retrato de la tía Pepa es una obra maestra del periodo de formación del joven Picasso “en la que el virtuosismo rivaliza con la profundidad, como si ambos quisieran primacía”. La obra fue donada al Museu Picasso de Barcelona por el propio Picasso en 1970.',
 'http://www.bcn.cat/museupicasso/imatges/lacoleccio/highlights/mpb110-010.jpg');



